name: CI
on:
  push:
    tags:
        - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '1.20.2'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
